### ISSUE TITLE
dark mode filter images

### ISSUE THREAD

**Issue by AndrewHaglund** [AndrewHaglund/AndrewHaglund.github.io#3]
[article](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/) then ⌘F "Dark Mode Images"

> … decrease the brightness and contrast of images so it looks comfortable against a dark background. Bright images on dark backgrounds can be jarring.

something like:
```css
/* Apply the filter directly on the body tag */
body.dark-theme img {
  filter: brightness(.8) contrast(1.2);
}
 
/* Or apply it via media query */
@media (prefers-color-scheme: dark) {
  img {
    filter: brightness(.8) contrast(1.2);
  }
}
```
